version: '3.7'
services:
  springboot-app:
    build:
      context: .
    container_name: spring-boot-app
    image: raliashik/technical-exercise:1.0
    ports:
      - "8080:8080"
    networks:
      - common-bridge-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/test_db
      - SPRING_DATASOURCE_USERNAME=testUser
      - SPRING_DATASOURCE_PASSWORD=testPassword
networks:
  common-bridge-network:
    external: true

